name: Deploy to WordPress.org
on:
  release:
    types: [released]

  # Allow manually triggering the workflow.
  workflow_dispatch:
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Populate Changelog
        run: node .github/workflows/changelog.js
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ad-code-manager
