name: Run PHPUnit

on:
  # Run on all pushes and on all pull requests.
  # Prevent the "push" build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - "**.md"
  pull_request:

  # Allow manually triggering the workflow.
  workflow_dispatch:

# Disable all permissions by default. Enable specific permissions per job.
permissions: {}

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: WP ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    env:
      WP_VERSION: ${{ matrix.wordpress }}

    strategy:
      matrix:
        include:
          # Check lowest supported WP version, with the lowest supported PHP.
          - wordpress: '6.4'
            php: '7.4'
          # Check latest WP with the latest PHP.
          - wordpress: 'master'
            php: 'latest'
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install wordpress environment
        run: npm install -g @wordpress/env

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${TOOL_CACHE}/php.json"
        env:
          TOOL_CACHE: ${{ runner.tool_cache }}

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${TOOL_CACHE}/phpunit.json"
        env:
          TOOL_CACHE: ${{ runner.tool_cache }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Setup wp-env
        run: wp-env start
        env:
          WP_ENV_CORE: WordPress/WordPress#${{ matrix.wordpress }}

      - name: Run integration tests
        run: composer test:integration --no-interaction
